version: "3.3"
services:
  sre-insights-admin-backend:
    build: .
    container_name: sre-insights-admin-backend
    image: sre-insights-admin-backend:1.6.0
    restart: unless-stopped
    ports:
      - "18000:18000"
    environment:
      - DATABASE_URL=postgresql://sreintern:TxSyHPDoaw44396z@34.135.5.178/sreinsights_dcl
